# Generated by Django 5.1.1 on 2025-01-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicationApartmentMediation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="status",
        ),
        migrations.AddField(
            model_name="user",
            name="status1",
            field=models.CharField(
                choices=[
                    ("BUYER", "Buyer"),
                    ("SELLER", "Seller"),
                    ("BUYER_AND_SELLER", "Buyer_and_seller"),
                    ("MEDIATOR", "Mediator"),
                ],
                default="BUYER",
                max_length=17,
            ),
        ),
    ]
