# Generated by Django 5.1.5 on 2025-01-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicationApartmentMediation", "0002_remove_user_status_user_status1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="status1",
            new_name="status",
        ),
        migrations.RemoveField(
            model_name="image",
            name="images",
        ),
        migrations.AddField(
            model_name="image",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
